In [1]:
import torch

In [2]:
# Declaring 2d tensor.
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
A = torch.tensor(a)
print(A)
print(A.ndimension())
print(A.shape)
print(A.size())
print(A.numel()) # To obtain number of elements in tensor.

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])
torch.Size([3, 3])
9


In [3]:
# Indexing.
print(A[0][2])
# Slicing.
print(A[0, 1:3])
print(A[1:3, 0])

tensor(3)
tensor([2, 3])
tensor([4, 7])


In [4]:
# Basic operations.
# Addition.
X = torch.tensor([[1, 2], [3, 4]])
Y = torch.tensor([[5, 6], [7, 8]])
print(X+Y)

# Multiply by a scalar.
print(2*X)

# Hadamard product.
print(X*Y)

# Matrix multiplication.
# Column of X must be equal to rows of Y.
print(torch.mm(X,Y))

tensor([[ 6,  8],
        [10, 12]])
tensor([[2, 4],
        [6, 8]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]])
