In [12]:
import torch

In [13]:
# Parameters gradient is required.
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

In [14]:
# Simple prediction function.
def forward(x):
    y = w*x + b
    return y

x = torch.tensor([1])
print(forward(x))

tensor([1.], grad_fn=<AddBackward0>)


In [15]:
# Multiple dimension input.
x = torch.tensor([[1], [2]])

yhat = forward(x)
print(yhat)

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [16]:
# inbuilt class.
from torch.nn import Linear

torch.manual_seed(1)

model = Linear(in_features=1, out_features=1)

print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [17]:
x = torch.tensor([1.0])

print(model(x)) # We don't have to call forward.

tensor([0.0739], grad_fn=<AddBackward0>)


In [18]:
# Custom modules.
# Custom module can contain multiple models and used in building complex models.
import torch.nn as nn

# Custom modeules are classes.
# These classes are subclasses of nn module.
class LR(nn.Module):
    
    def __init__(self, in_size, out_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(in_size, out_size)
            
    def forward(self, x): # We don't have to call it, just use paranthesis. It behaves like call method.
        out = self.linear(x)
        return out

In [19]:
model = LR(1,1)

model.state_dict()['linear.weight'].data[0] = torch.tensor([0.5153]) # For changing values.
model.state_dict()['linear.bias'].data[0] = torch.tensor([-0.4414])

print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [20]:
x = torch.tensor([1.0])
yhat = model(x)
print(yhat)

tensor([0.0739], grad_fn=<AddBackward0>)


In [21]:
# state_dict is dictionary containing the parameters.
print("Dictionary:", model.state_dict())
print("Keys:", model.state_dict().keys())
print("Values:",model.state_dict().values())

Dictionary: OrderedDict([('linear.weight', tensor([[0.5153]])), ('linear.bias', tensor([-0.4414]))])
Keys: odict_keys(['linear.weight', 'linear.bias'])
Values: odict_values([tensor([[0.5153]]), tensor([-0.4414])])
